source 'git@bitbucket.org:cabosoft-mobile/cabopods-ios.git'
source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

target 'autoinit_Tests' do
  platform :ios, '9.0'
  pod 'autoinit', :path => '../'
  
  
end
