source 'git@bitbucket.org:cabosoft-mobile/cabopods-ios.git'
source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

target 'autoinit_Example' do
	platform :ios, '9.0'
	pod 'autoinit', :path => '../'
	pod 'DBC'

	target 'autoinit_ExampleTests' do
		inherit! :search_paths
		pod 'DBC'
	end
end
